-- MySQL Script generated by MySQL Workbench
-- Fri Jul 15 01:20:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tasti
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tasti` ;

-- -----------------------------------------------------
-- Schema tasti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tasti` DEFAULT CHARACTER SET utf8mb4 ;
USE `tasti` ;

-- -----------------------------------------------------
-- Table `tasti`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasti`.`usuario` ;

CREATE TABLE IF NOT EXISTS `tasti`.`usuario` (
  `cui` INT(8) NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  `correo_electronico` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `estado_cuenta` INT(1) NOT NULL,
  PRIMARY KEY (`cui`),
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC),
  UNIQUE INDEX `cui_UNIQUE` (`cui` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tasti`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasti`.`administrador` ;

CREATE TABLE IF NOT EXISTS `tasti`.`administrador` (
  `cui` INT(8) NOT NULL,
  PRIMARY KEY (`cui`),
  UNIQUE INDEX `cui_UNIQUE` (`cui` ASC),
  CONSTRAINT `cui`
    FOREIGN KEY (`cui`)
    REFERENCES `tasti`.`usuario` (`cui`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tasti`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasti`.`curso` ;

CREATE TABLE IF NOT EXISTS `tasti`.`curso` (
  `idcurso` INT(8) NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  `anio` INT(1) NOT NULL,
  `semestre` INT(1) NOT NULL,
  PRIMARY KEY (`idcurso`),
  UNIQUE INDEX `idcurso_UNIQUE` (`idcurso` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tasti`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasti`.`perfil` ;

CREATE TABLE IF NOT EXISTS `tasti`.`perfil` (
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  `cui` INT(8) NOT NULL,
  PRIMARY KEY (`cui`),
  UNIQUE INDEX `cui_UNIQUE` (`cui` ASC),
  CONSTRAINT `cui_user`
    FOREIGN KEY (`cui`)
    REFERENCES `tasti`.`usuario` (`cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tasti`.`pregunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasti`.`pregunta` ;

CREATE TABLE IF NOT EXISTS `tasti`.`pregunta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `curso` INT(8) NOT NULL,
  `tema` VARCHAR(45) NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL,
  `cui_usuario` INT(8) NOT NULL,
  `disponibilidad` LONGTEXT NOT NULL,
  `estado` INT(1) NOT NULL,
  `fecha_limite` DATETIME NOT NULL,
  `cui_mentor` INT(8) NULL DEFAULT NULL,
  `fecha_meet` DATETIME NULL DEFAULT NULL,
  `link_meet` VARCHAR(45) NULL DEFAULT NULL,
  `reunion_privada` INT(1) NULL DEFAULT NULL,
  `max_participantes` INT(2) NULL DEFAULT NULL,
  `cupos_disponibles` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `cui_pregunta_idx` (`cui_usuario` ASC),
  INDEX `cui_mentor_idx` (`cui_mentor` ASC),
  INDEX `id_curso_idx` (`curso` ASC),
  CONSTRAINT `cui_men`
    FOREIGN KEY (`cui_mentor`)
    REFERENCES `tasti`.`usuario` (`cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cui_owner`
    FOREIGN KEY (`cui_usuario`)
    REFERENCES `tasti`.`usuario` (`cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_curso`
    FOREIGN KEY (`curso`)
    REFERENCES `tasti`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tasti`.`pregunta_no_rechazada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasti`.`pregunta_no_rechazada` ;

CREATE TABLE IF NOT EXISTS `tasti`.`pregunta_no_rechazada` (
  `id` INT(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `id_queu`
    FOREIGN KEY (`id`)
    REFERENCES `tasti`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tasti`.`pregunta_rechazada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasti`.`pregunta_rechazada` ;

CREATE TABLE IF NOT EXISTS `tasti`.`pregunta_rechazada` (
  `id_pregunta` INT(8) NOT NULL,
  PRIMARY KEY (`id_pregunta`),
  UNIQUE INDEX `id_pregunta_UNIQUE` (`id_pregunta` ASC),
  CONSTRAINT `pregunta_id`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `tasti`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tasti`.`reunion_publica-participantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasti`.`reunion_publica-participantes` ;

CREATE TABLE IF NOT EXISTS `tasti`.`reunion_publica-participantes` (
  `id_pregunta` INT(11) NOT NULL,
  `cui_participante` INT(8) NOT NULL,
  PRIMARY KEY (`id_pregunta`, `cui_participante`),
  INDEX `id_user_idx` (`cui_participante` ASC),
  CONSTRAINT `cui-userr`
    FOREIGN KEY (`cui_participante`)
    REFERENCES `tasti`.`usuario` (`cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_question`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `tasti`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tasti`.`solicitud_registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasti`.`solicitud_registro` ;

CREATE TABLE IF NOT EXISTS `tasti`.`solicitud_registro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NOT NULL,
  `user_cui` INT(8) NOT NULL,
  `dni` INT(8) NOT NULL,
  `estado` INT(1) NOT NULL,
  `admin_encargado` INT(8) NULL DEFAULT NULL,
  `fecha_atencion` DATETIME NULL DEFAULT NULL,
  `admin_nota` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `cui_admin_idx` (`admin_encargado` ASC),
  INDEX `cui_cuenta_idx` (`user_cui` ASC),
  CONSTRAINT `cui_admin`
    FOREIGN KEY (`admin_encargado`)
    REFERENCES `tasti`.`administrador` (`cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cui_cuenta`
    FOREIGN KEY (`user_cui`)
    REFERENCES `tasti`.`usuario` (`cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tasti`.`solicitud_revision_pregunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasti`.`solicitud_revision_pregunta` ;

CREATE TABLE IF NOT EXISTS `tasti`.`solicitud_revision_pregunta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT(11) NOT NULL,
  `cui_usuario` INT(8) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `razon` LONGTEXT NOT NULL,
  `estado` INT(1) NOT NULL,
  `cui_admin` INT(8) NULL DEFAULT NULL,
  `admin_nota` LONGTEXT NULL DEFAULT NULL,
  `fecha_solucion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_pregunta_UNIQUE` (`id_pregunta` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_cui_idx` (`cui_usuario` ASC),
  INDEX `id_pregunta_idx` (`id_pregunta` ASC),
  INDEX `admin_cui_idx` (`cui_admin` ASC),
  CONSTRAINT `admin_cui`
    FOREIGN KEY (`cui_admin`)
    REFERENCES `tasti`.`administrador` (`cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pre`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `tasti`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_cui`
    FOREIGN KEY (`cui_usuario`)
    REFERENCES `tasti`.`usuario` (`cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
